[package]
name = "temperature"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.0", features = ["v4"] }
tokio = { version = "1.1.0", features = ["full"] }
scylla = { version = "1.0", features = ["chrono-04"] }
futures = "0.3.6"
chrono = "0.4.0"
